### ISSUE TITLE
confusing explanation of kernel snaps

### ISSUE THREAD

**Issue by elopio** [canonical-websites/tutorials.ubuntu.com#102]
On https://tutorials.ubuntu.com/tutorial/create-your-own-core-image#2, in the kernel section it says:

"It doesn't limit itself to that as other parts like drivers are also part of this."

I find this confusing. My english is not good enough to find a perfect sentence, but what about:

It doesn't limit itself to the kernel, as it includes other parts like drivers.

**Comment by WillMoggridge** [comment]
Thankyou, I have flagged this up on the [source document](https://docs.google.com/document/d/172iM3jTkg2os8HgqtSpVug3IR5pjqS2zz607hTi3KVg/edit#).

**Comment by didrocks** [comment]
+1 on your suggestion, better than mine. Feel free to close it @WillMoggridge
