### ISSUE TITLE
Grammar error

### ISSUE THREAD

**Issue by murraybd** [canonical-websites/tutorials.ubuntu.com#104]
https://tutorials.ubuntu.com/tutorial/create-first-snap?utm_source=snapcraft.io&utm_medium=buildsnapsindex&utm_campaign=tutorials#2

contains "It's so separated that you can" but would be better written as "It's separated so that you can".

**Comment by WillMoggridge** [comment]
Thanks, this has been proposed to the upstream source document

**Comment by matthewpaulthomas** [comment]
This looks fixed now.
