### ISSUE TITLE
Extraneous word

### ISSUE THREAD

**Issue by murraybd** [canonical-websites/tutorials.ubuntu.com#105]
The following page:

https://tutorials.ubuntu.com/tutorial/create-first-snap?utm_source=snapcraft.io&utm_medium=buildsnapsindex&utm_campaign=tutorials#2

contains:

"To build hello this, simply add the following to your snapcraft.yaml file:"

I don't know what the word this is doing in that sentence.

**Comment by WillMoggridge** [comment]
Thanks, this has been proposed to the source document!

**Comment by matthewpaulthomas** [comment]
This looks fixed now.

(BTW, for future issues, a more specific title would help others searching.)
