### ISSUE TITLE
Characters are not correctly displayed on the Chrome browser

### ISSUE THREAD

**Issue by liu-xiao-guo** [canonical-websites/tutorials.ubuntu.com#106]
I am now accessing tutorials.ubuntu.com. In my Chrome browser, it shows sth like http://imgur.com/a/Vw6vt. Some strings are overlapped. However, it works well in firefox browser.

**Comment by WillMoggridge** [comment]
Could you confirm if this is still affecting you? If so, can I ask which operating system you are using?
