### ISSUE TITLE
Word choice / usage correction

### ISSUE THREAD

**Issue by dklickman** [canonical-websites/tutorials.ubuntu.com#107]
https://tutorials.ubuntu.com/tutorial/create-first-snap#6 
Under the header "Register a new snap name" 
>> "If the name is already reserved, you can either despite that name or just pick a new one."

I assume "despite" should be "dispute" if the name is already taken.

**Comment by WillMoggridge** [comment]
Thanks! I have proposed this to our source document

**Comment by matthewpaulthomas** [comment]
This looks fixed now.

(BTW, for future issues, a more specific title would help others searching.)
