### ISSUE TITLE
[Cards] Tags &  Description should follow the card guidelines

### ISSUE THREAD

**Issue by joanasa89** [canonical-websites/tutorials.ubuntu.com#110]
- Tags: maximum of 4 tags per card
- Description: Maximum of 5 lines

![design_guidelines](https://cloud.githubusercontent.com/assets/21334617/22735214/b215b9bc-edf0-11e6-92e7-dac6ca7ee4d9.jpg)

**Comment by WillMoggridge** [comment]
This design has changed so I will close this
