### ISSUE TITLE
[search] tutorials content is not indexed in google

### ISSUE THREAD

**Issue by ghost** [canonical-websites/tutorials.ubuntu.com#116]

**Comment by WillMoggridge** [comment]
Some talk revolving around this subject:
https://github.com/PolymerElements/polymer-starter-kit/issues/367

**Comment by didrocks** [comment]
You can use the google index tools to at specify descriptions and update its content based on existing tutorials description and such. Then, you can export a static version of main page (generated) for SEO, via service worker for instance.

**Comment by WillMoggridge** [comment]
Yeah, I am very interested in building static versions of pages for that reason. I think it requires investigation to backend tooling to generate it. I think I read somewhere of people usind express.js to generate them but I need to see if I was correct or mistaken.

I'm not sure service workers are able to do this but I am no service worker expert. May be that is possible.

**Comment by WillMoggridge** [comment]
This would greatly improved with #339

**Comment by WillMoggridge** [comment]
Closing this as content is indexing now
