### ISSUE TITLE
Please provide a simple update/add/remove mechanism describe in README.md

### ISSUE THREAD

**Issue by didrocks** [canonical-websites/tutorials.ubuntu.com#117]
I think I need in the `README.md` (as the one updated is still mine and I doubt it works as it doesn't mention about the config file in `https://github.com/ubuntudesign/tutorials.ubuntu.com/blob/master/config/google-documents`.)

Basically:
* How to add a tutorial
* How to update a tutorial. If update is automated, what frequency is it?
* How to remove a tutorial.

**Comment by WillMoggridge** [comment]
Sure, I can add more info to the repository for the new process.
Currently it is automated during build, which is manually fired.

In short, they are set in the `config/codelabs.yaml` file

**Comment by caldav** [comment]
Since most of this process has changed, I think we can close this report. Feel free to re-open if you disagree.
