### ISSUE TITLE
Timeline for markdown

### ISSUE THREAD

**Issue by samnazarko** [canonical-websites/tutorials.ubuntu.com#123]
Hello

I stumbled across the Ubuntu tutorials website recently and thought it was very well laid out. I don't really use Google Docs, but Markdown sounds like a perfect way to develop tutorials. I'm looking at using this tutorials project for our open source project OSMC.

* Do you have a timeline / ETA for when Markdown will be implemented? Is there a list of what needs to be done so I can take a look at contributing?
* Will the Markdown be buildable from a directory in-tree, or will it have to be hosted somewhere else?

Thanks

Sam

**Comment by didrocks** [comment]
No real timeline for this. However, I did fix some bugs in the google claat importer tool for Markdown, got some of them merged upstream even!
As soon as we have enough tutorials published, I'll probably dive into this more to gather a list of what needs to be done.

However, I do agree this will be a better way for getting people to contribute! We need though at least port the formatting guidelines, create a template, port current tutorials.
Ideally, they will be in tree with a very simple way to rebuild everything quickly for having a quick preview (or even having live preview?)

**Comment by evilnick** [comment]
Markdown is now supported (thanks @didrocks!), and although we are still working on things, you can get started (see examples in /tutorials ).

**Comment by samnazarko** [comment]
Thanks for letting me know. This is great.
