### ISSUE TITLE
Running ./bin/build-tutorials getting an error 

### ISSUE THREAD

**Issue by thyeun** [canonical-websites/tutorials.ubuntu.com#145]
OS : ubuntu 16.04

Try to import live content with ./bin/build-tutorials

than i'm getting the below error
bash: ./bin/build-tutorials: No such file or directory

So what goes wrong?

**Comment by WillMoggridge** [comment]
Did you manage to run this? Can I check you have opened a terminal and `cd` to this project?

As a note, this will likely change in the next few days, to ./bin/generate.

**Comment by thyeun** [comment]
@WillMoggridge thanks, i solve before 1st Apr, and sorry for not closing this.

**Comment by WillMoggridge** [comment]
Ah, thanks. That isn't a problem at all. :D
