### ISSUE TITLE
[Chrome & Firefoxe/ Mac] Mobile - Sort filters - Change width

### ISSUE THREAD

**Issue by joanasa89** [canonical-websites/tutorials.ubuntu.com#154]
Sort filters should be 
- aligned with 'filters' and 'search bar' 
- full width.

**Comment by WillMoggridge** [comment]
This looks fixed

**Comment by WillMoggridge** [comment]
Actually, it applies in a medium width resolution. The filters change to full width before the sort option.

**Comment by WillMoggridge** [comment]
Closing in favour of #165
