### ISSUE TITLE
[Safar/Mac]  Search bar - increase height

### ISSUE THREAD

**Issue by joanasa89** [canonical-websites/tutorials.ubuntu.com#155]
Desktop - Search bar dimensions should match the original design (38px)
Mobile - Increase height to 38px ; aligned with filters and make it full width

**Comment by WillMoggridge** [comment]
The height on the search bar is 28px + 6px padding + 1px border
The filters are 30px + 6px padding + 1px border.

We should increase the search bar to match the filter and search bars.

**Comment by WillMoggridge** [comment]
I am going to add this to #165 which is related to resizing these fields.
