### ISSUE TITLE
Unify search/filter/sort input width and height

### ISSUE THREAD

**Issue by joanasa89** [canonical-websites/tutorials.ubuntu.com#165]
Search bar, sort and filters should all have consistent styling.

- They should all be full width from medium (768) breakpoint and smaller
- They should be the same height

<img width="756" alt="screen shot 2017-03-22 at 14 15 15" src="https://cloud.githubusercontent.com/assets/21334617/24202100/00498728-0f0a-11e7-9e21-4841280f8603.png">

---

The height on the search bar is 28px + 6px padding + 1px border
The filters are 30px + 6px padding + 1px border.

We should increase the search bar to match the filter and search bars.

**Comment by WillMoggridge** [comment]
When fixing this issue, be sure that the width is correct at all sizes
