### ISSUE TITLE
Snap a website step 5 omits sudo and snap install & connect and then still does not run

### ISSUE THREAD

**Issue by tstephen** [canonical-websites/tutorials.ubuntu.com#175]
Using 16.04. On https://tutorials.ubuntu.com/tutorial/snap-a-website#4 when attempting to launch with `ubuntu-webapp` I was prompted:

```
$ ubuntu-webapp
You need to connect this snap to the ubuntu app platform snap.

You can do this with those commands:
snap install ubuntu-app-platform
snap connect ubuntu-webapp:platform ubuntu-app-platform:platform
```
Doing so creates an error (`try with sudo`) After doing so I then receive the same error again. 

Please advise what to check / diagnostics to run.

**Comment by WillMoggridge** [comment]
@didrocks would you be able to help or point in the right direction?

**Comment by didrocks** [comment]
Hey @tstephen, the tutorial page you are pointing at clearly states that you will see that message, then, there is a command to discare namespace, connect the interface and rerunning it. I just did rerun through it and it's working, are you sure you followed the tutorial step by step?

**Comment by WillMoggridge** [comment]
As there has been no reply in some time, I will close this but it can be reopened if needed.
