### ISSUE TITLE
Intel Joule tutorial: List that a power supply is required

### ISSUE THREAD

**Issue by flexiondotorg** [canonical-websites/tutorials.ubuntu.com#176]
The Intel Joule does not come with a power supply, the documentation should inform the reader what power supply is required because, unlike common SBCs, it can't be powered via USB. These are the specification for an Intel Joule power adapter:

A DC power supply (listed LPS or Class 2) with an output of 12 VDC at 3 Amps through a center positive barrel jack (5.5mm outer diameter, 2.1mm inner diameter with a barrel length of ~9-10mm).

**Comment by WillMoggridge** [comment]
Thanks for flagging this, I will point it to the tutorial team

**Comment by pmatulis** [comment]
Closed via #346.
