### ISSUE TITLE
There are no instructions for how to fix a tutorial

### ISSUE THREAD

**Issue by elopio** [canonical-websites/tutorials.ubuntu.com#181]
I found no instructions for how to access the source google doc, how to make suggestions in there or how to request permission to edit it.

If somebody wants to fix one of the reported bugs, like fixing a typo in one of the tutorials, it's not clear what to do.

**Comment by ryanleesipes** [comment]
I propose opening the Google Doc so that anyone may view or comment on it. If that is abused then close the document.

**Comment by didrocks** [comment]
Our current mindset is rather to migrate all tutorials to markdown. That way, the flow to fix them will be really obvious. I'm currently building the deployment tooling for this (see https://github.com/ubuntu/tutorial-deployment) and fixing google's codelab converter for markdown which seems to not have been really used as even image importing was broken as well as step generations.
My goal is to be able to still offer live-preview for tutorials.

Any help then to migrate the tutorial guidelines and defining a markdown template will be more than welcome!

**Comment by elopio** [comment]
@didrocks sounds good, but in the meantime we can make corrections to the docs, so when they are migrated to markdown they will have a few things already fixed. Maybe allow @ryanleesipes and me to make comments?

**Comment by didrocks** [comment]
Sure, this is now done!

**Comment by WillMoggridge** [comment]
I will close this then, if it is done. If not, do reopen it.
