### ISSUE TITLE
Change last page of Basic Snap Usage tutorial

### ISSUE THREAD

**Issue by ryanleesipes** [canonical-websites/tutorials.ubuntu.com#182]
On [this page](https://tutorials.ubuntu.com/tutorial/basic-snap-usage#5), change the bullet point:
>Join the snapcraft.io community by subscribing to our mailing list.

to:
Join the snapcraft.io community, visit the [Snapcraft Forum](https://forum.snapcraft.io) to get involved.

**Comment by didrocks** [comment]
We do have a forum? I'm unsure we want to invite people there as there has been no official announcement about it on the mailing list.

**Comment by evandandrea** [comment]
This appears to be resolved in production.
