### ISSUE TITLE
Snap a Website - Step 4 - No ubuntu-app-platform snap?

### ISSUE THREAD

**Issue by dbuday** [canonical-websites/tutorials.ubuntu.com#188]
When i try:
(sudo) snap install ubuntu-app-platform

I get:
error: cannot install "ubuntu-app-platform": snap not found

I tried it few times. I even can't find it using  'snap find'
Cannot proceed with tutorial.

**Comment by caldav** [comment]
As far as I can tell, ubuntu-app-platform has only been published for amd64, on which architecture are you getting this error?

**Comment by dbuday** [comment]
Well, that's my answer then - i use 32-bit architecture.

Thanks for the answer.
I guess i need new computer to proceed with this tutorial.
