### ISSUE TITLE
[How to snap a website] The tutorial need to add a PPA, so it's impossible to build the snap with build.snapcraft.io service

### ISSUE THREAD

**Issue by Winael** [canonical-websites/tutorials.ubuntu.com#194]
Hi

I follow the tutorial _How to snap a website_ to snap my company website, published my work on Github and try to use the build.snapcraft.io service to automatically build and publish my snap.

Unfortunatelly, it doesn't work because ubuntu-app-platform part need librairies that not available in 16.04. A PPA is needed to be able to build the snap, that's not an option for the build.snapcraft.io service according to sergiusens (https://forum.snapcraft.io/t/error-when-using-build-snapcraft-io-to-build-webapps-snap)

So for a better exeperience, maybe the tutorial have to be fixed to adopt a more snappy way to includes the needed librairies

Cheers
Winael

**Comment by WillMoggridge** [comment]
Thanks for raising this. I have flagged this up to the Tutorials team.

**Comment by evandandrea** [comment]
I believe that tutorial is [being dropped in favour of Electron](https://forum.snapcraft.io/t/error-when-using-build-snapcraft-io-to-build-webapps-snap/310/8).
