### ISSUE TITLE
Correctly 404 for missing pages

### ISSUE THREAD

**Issue by WillMoggridge** [canonical-websites/tutorials.ubuntu.com#200]
When loading an incorrect URL, the website should return a full 404 page and response code.

**Comment by frankiegranato** [comment]
@WillMoggridge & @deadlight Does this issue describe work to be done only for tutorials.ubuntu.com or also for ubuntu.com?

**Comment by WillMoggridge** [comment]
This is just for Tutorials. We can look more at other projects as well but this issue itself is limited to this scope.
