### ISSUE TITLE
All desktop tutorials should be tagged as desktop

### ISSUE THREAD

**Issue by campbieil** [canonical-websites/tutorials.ubuntu.com#230]
At this moment all desktop tutorials are not tagged as desktop, therefore on the front page it is not possible to only select desktop tutorials using the topics drop down

**Comment by didrocks** [comment]
I guess the issue is more that the list of categories have been hardcoded. It used to be in the api json file (generated when gathering tutorials) but was replaced by a hardcoded version when the site went to production. I guess a dynamic list needs to be reintroduced.

**Comment by anthonydillon** [comment]
This is true also for the JAAS/Juju tutorials.

**Comment by evilnick** [comment]
and will be true for the LXD tutorials we want to add

**Comment by WillMoggridge** [comment]
I believe this should be closed now as the Docs team has been working on categorising the content.
