### ISSUE TITLE
Create a bootable USB stick on macOS

### ISSUE THREAD

**Issue by BLRodriguez** [canonical-websites/tutorials.ubuntu.com#278]
I followed the steps and the outcome was a bootable USB that only works with a PC.
But I found this in the help community and that worked :-) https://help.ubuntu.com/community/How%20to%20install%20Ubuntu%20on%20MacBook%20using%20USB%20Stick

**Comment by evilnick** [comment]
Thanks for the feedback, we will update this tutorial ASAP!

**Comment by jlbrewster** [comment]
Thanks for leaving bad info up for more than 2 years!

**Comment by jlbrewster** [comment]
Use NetBootIn.
