### ISSUE TITLE
MacOS Bootable USB Tutorial Uses UNetbootin, Install Criticises It

### ISSUE THREAD

**Issue by DarrenACollins** [canonical-websites/tutorials.ubuntu.com#305]
It's weird that the "Create a bootable USB stick on macOS" instructions tell the user to use UNetbootin to create the USB stick, but when you run the Ubuntu 16.x LTS install you get a screen advising that UNetbootin creates unreliable USB sticks, and advises you to use something else.

This is confusing for new users, and the warning screen doesn't give you enough information on how to create the USB stick "properly".

When following Ubuntu's own directions on how to install Ubuntu, I expect everything to just work smoothly.

**Comment by Ij888** [comment]
![screenshot 2017-08-05 22 46 01](https://user-images.githubusercontent.com/2773674/28999111-64b4b388-7a33-11e7-8553-c9a6550f34ed.png)

I got this issue. After creating the USB stick, it tells you the stick can not boot off a mac.

**Comment by DarrenACollins** [comment]
That's not the message I was talking about - I was creating a USB stick on a Mac, for installing on a non-Mac PC (my new server). When you actually do the install on the PC from the USB stick, it gives you the UNetbootin warning.

**Comment by degville** [comment]
Thanks for flagging these issues, and I think you're totally correct about the inconsistent messaging. (UNetbootin is playing it safe with the Mac boot warning), but I think we should replace UNetbootin in this tutorial with an open source alternative - maybe something like https://etcher.io/. I'll test it out, or find an alternative that works, and update the tutorial.

**Comment by DarrenACollins** [comment]
Awesome, great to make things smooth for new players. Thanks!
