### ISSUE TITLE
"How to verify" ISO download instructions references a previous version of 16.04.x LTS

### ISSUE THREAD

**Issue by brettbits** [canonical-websites/tutorials.ubuntu.com#307]
On this webpage:

https://tutorials.ubuntu.com/tutorial/tutorial-how-to-verify-ubuntu?_ga=2.244720771.726094770.1502558794-320038252.1502558794#1

the link indicates that it provides resources for 16.04.2. However, following the link opens a page for 16.04.3. Simply updating the link text to the newest LTS version of 16.04.3 would be nice to have.

First screenshot shows the link text. Second screenshot shows the title of the page that was opened when I followed the link.

<img width="803" alt="screen shot 2017-08-12 at 10 39 38 am" src="https://user-images.githubusercontent.com/1459368/29243023-9bc08b6a-7f4a-11e7-93cb-7eaf03859e5c.png">

<img width="670" alt="screen shot 2017-08-12 at 10 39 44 am" src="https://user-images.githubusercontent.com/1459368/29243025-9f0bb1aa-7f4a-11e7-8660-8c43ef36df51.png">

**Comment by caldav** [comment]
Fixed by #595
