### ISSUE TITLE
UNetbootin failed for me on macOS Sierra

### ISSUE THREAD

**Issue by nikgraf** [canonical-websites/tutorials.ubuntu.com#310]
UNetbootin failed for me on macOS Sierra. I moved it to application, right clicked and confirmed with open. It crashed before seeing any UI. I found a related issue here https://github.com/unetbootin/unetbootin/issues/131

I moved on and used https://github.com/resin-io/etcher instead which worked fine. If others have the same issue it might be worth considering to switch.

**Comment by degville** [comment]
Thanks for letting us know - we've now switched the instructions to use Etcher (see also #305).

**Comment by nikgraf** [comment]
👍  glad to hear
