### ISSUE TITLE
Content of card touching card edge

### ISSUE THREAD

**Issue by yaili** [canonical-websites/tutorials.ubuntu.com#312]
In the tutorials homepage the content section of the card, below the title area, doesn't have any padding, there should be some padding:

<img width="356" alt="screen shot 2017-08-17 at 15 39 21" src="https://user-images.githubusercontent.com/223966/29417811-5f534f5c-8362-11e7-9ad5-cccbcc9725de.png">

**Comment by caldav** [comment]
FYI: this must be fairly recent, it was only happening on local deployments and not once deployed on staging or prod three weeks ago.

**Comment by WillMoggridge** [comment]
Yeah, that is what I thought.
Well, I am going to look into this now and try and get it sorted.
