### ISSUE TITLE
Running tutorials with docker

### ISSUE THREAD

**Issue by abelardolg** [canonical-websites/tutorials.ubuntu.com#325]
Hi there,

Once I have installed docker in Xubuntu, I run this command:

> ./run

but this message was displayed:

> Error: (username) not in docker group
===
Please add this user to the docker group, e.g. with: $ newgrp docker

When I run the last statement and I entered my password, this other message was displayed:
> newgrp: failed to crypt password with previous salt: Invalid argument

How should I continue in order to run Ubuntu tutorials?

Instructions should be clearer and to be documented in order to cover these issues.

Note I attach a log file in order to be more detailed this issue:
[npm-debug.txt](https://github.com/canonical-websites/tutorials.ubuntu.com/files/1287046/npm-debug.txt)

Kindest regards.

**Comment by deadlight** [comment]
You user needs to be in the docker group to manage docker on your machine but the error message doesn't give full instructions. You can find more details about configuring your user here: https://docs.docker.com/engine/installation/linux/linux-postinstall/

I hope that that helps.
Karl

**Comment by battlemidget** [comment]
I realize this is an old bug, but I ran into this issue as well, running `sudo grpconv` fixed it for me.

Ref: https://bugs.launchpad.net/ubuntu/+source/shadow/+bug/1355111/comments/9
