### ISSUE TITLE
Verify Release Screenshot

### ISSUE THREAD

**Issue by SeaDude** [canonical-websites/tutorials.ubuntu.com#349]
[In this tutorial](https://tutorials.ubuntu.com/tutorial/tutorial-how-to-verify-ubuntu?backURL=%2F#2), there is no "screenshot" that is verified. The term "screenshot" here is not understood. 

I'm downloading keys from gpg server
Verifying _fingerprint_

But nothing related to screenshots. Please clarify. 

Thanks

**Comment by evilnick** [comment]
Yup, I don't know how that got in there - thanks for pointing it out
