### ISSUE TITLE
The header back button should respect the backURL parameter

### ISSUE THREAD

**Issue by caldav** [canonical-websites/tutorials.ubuntu.com#356]
This is a functionality that used to exist before the V1 release and that we are needing again.

Tutorials URLs allow a `backURL` parameter, that changes the behaviour of the header back button.

You can still see it when clicking on a tutorial card from the homepage:
https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-macos?backURL=%2F#0

Its purpose is to allow the back button to take the user back to a different website. For example, a tutorial linked from snapcraft.io woud use https://tutorials.ubuntu.com/tutorial/<tutorial>?backURL=https://snapcraft.io

This would help fix a part of https://github.com/canonical-websites/snapcraft.io-static-pages/issues/370

A former implementation of the feature can be seen here: https://github.com/ubuntu/codelabs/blob/master/src/codelabs/basic-snap-usage/index.ubuntu-template.html#L273

**Comment by matthewpaulthomas** [comment]
This looks related to #173.
