### ISSUE TITLE
Design of positive, neutral & negative feedback response icons

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/tutorials.ubuntu.com#362]
We are adding a user-feedback component to the last page of all tutorials on tutorials.ubuntu.com. 

We need a positive, neutral & negative response icon. I'm suggesting smiley faces in my sketch (jpg here: https://drive.google.com/open?id=0B2_PyaH0PaVmcVBpRk9QSnhOV00) but I'm open to other suggestions.
Can you help us with finding or creating appropriate icons for this type of context? If you can, I'll go ahead and make an issue on Github to describe this work.

There is also a copydoc for content: https://drive.google.com/open?id=1mowrfzN_ao6AcwxqjyV9jvgbMiv2xXHaxLE2wzTvspc

 ![Tutorials feedback Wireframe sketch.jpg](https://images.zenhubusercontent.com/593552bf51aa2c3057806d8c/e71407d4-ffa1-4ce0-a241-647f90bc9158)

**Comment by frankiegranato** [comment]
This is a screenshot shared by @WillMoggridge of how the working code looks at present: https://drive.google.com/open?id=0B2_PyaH0PaVmeWNqQ2UwcUhkeW84ODg3ajItcFdBRmktVGNn

**Comment by anthonydillon** [comment]
Can this be estimated please?

**Comment by caldav** [comment]
For reference, here is the first version impelemented 
![screenshot from 2017-10-20 10-06-49](https://user-images.githubusercontent.com/18480003/31811077-7f444304-b57e-11e7-9cb4-da65284abfe0.png)
