### ISSUE TITLE
Design enhancement of tutorials feedback & signup components - design

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/tutorials.ubuntu.com#373]
brief: https://docs.google.com/document/d/13FyNPNktBbiCCLt6hj1KLT0JmNlB6fJ3kSU9Xip-qd0/edit#

**Comment by michaelb17** [comment]
-- Duplicate Story --

Epic: https://app.zenhub.com/workspace/o/ubuntudesign/web-squad/issues/244
