### ISSUE TITLE
impossible to "create your first app"

### ISSUE THREAD

**Issue by saouinet** [canonical-websites/tutorials.ubuntu.com#377]
Hi, after an Ubuntu upgrade to 17.10, I wanted to start the "Create your fist app" 
when executing "sudo classic", I have the following message : 
....
Reading package lists... Done
cp: cannot stat '/etc/writable/hostname': No such file or directory

I'm stuck in place.

**Comment by caldav** [comment]
Hello and sorry for the delay! This step (installing the classic snap) is only relevant for Ubuntu Core installs (on a [raspberry pi](https://developer.ubuntu.com/core/get-started/raspberry-pi-2-3) for example). You can skip it on 17.10.
