### ISSUE TITLE
SHA256 not trustable

### ISSUE THREAD

**Issue by aduh95** [canonical-websites/tutorials.ubuntu.com#382]
Greetings!

I've just download the Ubuntu 17.10 Desktop ISO, and I wanted to check the integrity of the file.

I went on [this tutorial](https://tutorials.ubuntu.com/tutorial/tutorial-how-to-verify-ubuntu), and on the second step, I figure there is a problem: There is no secure links given, only plain HTTP (http://releases.ubuntu.com/17.10/).

What is the point of checking the hash if I can't trust the actual hash?

If this information is available on an other trustable server, we certainly should add the link to the tutorial. Otherwise, maybe it's time to consider adding TLS on releases.ubuntu.com!

**Comment by nottrobin** [comment]
Hi @aduh95, thanks for reaching out.

The [third step](https://tutorials.ubuntu.com/tutorial/tutorial-how-to-verify-ubuntu#2) of the tutorial you linked to mentions this issue explicitly:

> Note - some people question that if the site they are downloading from is not secure (many archive mirrors do not use SSL), how can they trust the signatures? The gpg fingerprint is checked against the Ubuntu keyserver, so if the signature matches, you know it is authentic no matter where/how it was downloaded!

So the answer is that the SHA256SUMS can be trusted by using its signature, SHA256SUMS.gpg alongside our GPG signatures from the Ubuntu keyserver which can be trusted. The tutorial walks you through how to do this, but it's basically:

``` bash
$ gpg --keyid-format long --keyserver hkp://keyserver.ubuntu.com --recv-keys 0x46181433FBB75451 0xD94AA3F0EFE21092

$ gpg --keyid-format long --verify SHA256SUMS.gpg SHA256SUMS
...
gpg: Good signature from "Ubuntu CD Image Automatic Signing Key <cdimage@ubuntu.com>" [unknown]
...

$ sha256sum -c SHA256SUMS 2>&1 | grep OK
ubuntu-18.04-desktop-amd64.iso: OK
```

We're aware that this process is somewhat cumbersome, and we're working on ways to improve the experience.
