### ISSUE TITLE
build.snapcraft.io snap never gets built is snapcraft.yaml is not found when repo is added

### ISSUE THREAD

**Issue by lucasrangit** [canonical-websites/tutorials.ubuntu.com#387]
Steps to reproduce:

1. Fork any project on https://github.com
1. Crate branch with any name (e.g. "snapcraft")
1. Push a snapcraft.yaml for a project named `anything-$USERNAME`
1. Use https://build.snapcraft.io to add repository
1. https://build.snapcraft.io will fail to find a `snapcraft.yaml`
1. Change repository's default branch on GitHub
1. https://build.snapcraft.io eventually detects and finds `snapcraft.yaml` 
1. Observe that a build is never started

**Comment by anthonydillon** [comment]
Issue moved to [canonical-websites/build.snapcraft.io #1036](https://github.com/canonical-websites/build.snapcraft.io/issues/1036) via [**ZenHub**](https://www.zenhub.com/)
