### ISSUE TITLE
[Install Ubuntu desktop] <增加如何制作Ubuntu U盘启动安装盘的细节>

### ISSUE THREAD

**Issue by haomengjie** [canonical-websites/tutorials.ubuntu.com#389]
<增加如何制作Ubuntu U盘启动安装盘的细节

现在的笔记本，大多不支持CD/DVD。多数使用U盘，所以，我希望增加制作Ubuntu U盘启动安装盘的更多信息
>

**Comment by evilnick** [comment]
There is already a tutorial for installing from a USB stick - https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-windows - and similar instructions for ubuntu and macOS. I think this covers the non-CD installation?

**Comment by anthonydillon** [comment]
Thank you.
