### ISSUE TITLE
How to verify your Ubuntu download: Broken box syntax

### ISSUE THREAD

**Issue by Geo1088** [canonical-websites/tutorials.ubuntu.com#397]
https://tutorials.ubuntu.com/tutorial/tutorial-how-to-verify-ubuntu#2

The page features a broken-looking section, reading `positive:Tip - On...` which I assume is a broken syntax to create a colored box or something similar.

Screenshot: https://i.imgur.com/jJYmWzY.png

**Comment by evilnick** [comment]
Fixed in #402
