### ISSUE TITLE
Tutorials - Homepage V2 design 'Event' pages

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/tutorials.ubuntu.com#425]

**Comment by michaelb17** [comment]
Proposed Concept:
The events template page follows the 'Tutorial Homepage' layout and structure with a configurable 'takeover' section allowing for bespoke copy and imagery.

![Event - Ubuntu Tutorials Home Template 1.jpg](https://images.zenhubusercontent.com/59e712dca468affe6df71a10/0a581f29-b25d-4246-8209-b0ca0cfe408a)

**Comment by frankiegranato** [comment]
@spencerbygraves can you review this when you get a moment please? I think it looks fine.

**Comment by spencerbygraves** [comment]
@frankiegranato tab spacing would need to follow Vanilla but fine otherwise.

**Comment by frankiegranato** [comment]
I'll pass your feedback about the tab spacing on to David Calle (@caldav). I think David is probably going to be handling much of these types of front end enhancements. However, unfortunately the tutorials site doesn't run on Vanilla so can you be a bit more specific with your instruction please?

**Comment by spencerbygraves** [comment]
@frankiegranato ok, I thought it would be using Vanilla. Even so, it would be good to match the Vanilla version of tabs where possible. They can be seen here - https://docs.vanillaframework.io/en/patterns/tabs
