### ISSUE TITLE
Arrows overlapping content

### ISSUE THREAD

**Issue by magdalena-mirowicz** [canonical-websites/tutorials.ubuntu.com#47]
On large screens arrows are sometimes overlapping tutorial page. It's not very consistent (sometimes it happens and sometimes not)

![screen shot 2017-01-13 at 16 54 21](https://cloud.githubusercontent.com/assets/16683435/21938003/581816a6-d9b1-11e6-925c-5501c03f482b.png)

**Comment by fcole90** [comment]
This happens on my Samsung Galaxy S4 too, using Chrome

**Comment by WillMoggridge** [comment]
Horzontal aligning of arrows/content should be fixed, I will close this.
