### ISSUE TITLE
Tutorial Wanted - Install the Arduino IDE for Ubuntu

### ISSUE THREAD

**Issue by evilnick** [canonical-websites/tutorials.ubuntu.com#480]
This tutorial will show the reader how to download and install the latest stable version of the Arduino IDE. It should also cover adding the user to the dialout group (so you can flash Arduino devices) and an explanation of the different devices used by common boards (e.g. ttyACM0 etc)

Some useful material for this is found on the Arduino website:

https://www.arduino.cc/en/Guide/Linux

**Comment by kaine119** [comment]
Hi, I'd like to work on this. 

May I assume that the user knows how to use the terminal, and have them use `apt` to install the Arduino IDE?

**Comment by coverme76** [comment]
Does [Amber Graner](https://twitter.com/youinubuntu) know about this request?
