### ISSUE TITLE
Tutorial Wanted - install and configure Apache

### ISSUE THREAD

**Issue by degville** [canonical-websites/tutorials.ubuntu.com#484]
This tutorial will cover the installation and configuration of Apache, concluding with a basic site the reader can build upon or swap-out.

The reader will be a moderately experienced Linux user who may be installing and configuring web-based services for their Ubuntu server for the first time. Terms such as 'Virtual Hosts' should be explained.

The following document may be useful:
https://help.ubuntu.com/lts/serverguide/httpd.html

**Comment by aden-chrome** [comment]
A pull request has been submitted: https://github.com/canonical-websites/tutorials.ubuntu.com/pull/515

**Comment by degville** [comment]
fixed with #515

**Comment by unixoid96** [comment]
error 
sudo cp 000-defualt.conf gci.conf
