### ISSUE TITLE
[Chrome/Chromium-based] All fonts are in bold

### ISSUE THREAD

**Issue by caldav** [canonical-websites/tutorials.ubuntu.com#511]
When viewed in Chrome or chromium-based browsers, all fonts are in bold.

![screenshot from 2017-11-29 16-04-47](https://user-images.githubusercontent.com/18480003/33381716-0e171a92-d51f-11e7-8404-ec69df7930d2.png)

This is a fairly recent issue (started a week ago).

The intended style can be seen in Firefox:

![screenshot from 2017-11-29 16-06-52](https://user-images.githubusercontent.com/18480003/33381822-5c85db00-d51f-11e7-9727-ba531f84a9ec.png)

**Comment by WillMoggridge** [comment]
Closing as I believe you have done some good work on this and it has been corrected.
