### ISSUE TITLE
Tutorial Wanted: How to recover password from Lastpass.com/?ac=1 when using bytemark eMail-provider.

### ISSUE THREAD

**Issue by 3DJetengine** [canonical-websites/tutorials.ubuntu.com#527]
after managing to update my aquarius 4.5 to upborts using the magicinstaller process and xubuntu 17.10, I have appeared to have lost my password to Lastpass.com

some helpful tutorial would help (without wikihow) in getting my password back back so that it is possible to use Launchpad,

and thereby [askubuntu.com](https://askubuntu.com/questions/tagged/xubuntu?sort=unanswered&pageSize=50&mixed=1).

**Comment by caldav** [comment]
I'm not sure what the relationship is between bytemark, lastpass and Ubuntu in this scenario, and how an Ubuntu tutorial would help. 

If the password was stored on the Ubuntu phone, then maybe you are suggesting a "Credentials backup" tutorial or a "File recovery" one (which are both good ideas).

If you need immediate help recovering this password, you may want to [check with LastPass directly](https://lastpass.com/support.php?cmd=showfaq&id=375).
