### ISSUE TITLE
Ubuntu should have a tutorial showing how to make a smb server. #GoogleCodeIn

### ISSUE THREAD

**Issue by akashk0000** [canonical-websites/tutorials.ubuntu.com#568]

**Comment by akashk0000** [comment]
Hey people, I am a participant of the Google Code In Contest. This task is about submitting a suggestion for a tutorial. The tutorial would be useful because some people don't want a lot of money to buy a server. They can save hundreds of dollars by installing their own server on an existing Ubuntu powered machine. There would be many benefits to having your own ubuntu server, you could use it as a nas or a plex server.
 - I hope anyone found this useful.

**Comment by caldav** [comment]
I believe [this tutorial](https://tutorials.ubuntu.com/tutorial/install-and-configure-samba) closes the issue, if you had something else in mind, feel free to re-open it.
