### ISSUE TITLE
feedback_url or feedback-link ?

### ISSUE THREAD

**Issue by abitrolly** [canonical-websites/tutorials.ubuntu.com#617]
Basic snap tutorial contains both -
https://github.com/canonical-websites/tutorials.ubuntu.com/blame/2164249484bc9fcde468f5e79197766dcb0b51c8/tutorials/packaging/basic-snap-usage/basic-snap-usage.md#L6

Is there a description of those parameters?

Should linter be updated to warn about unknown/deprecated fields? https://github.com/canonical-websites/tutorials.ubuntu.com/commit/2164249484bc9fcde468f5e79197766dcb0b51c8

**Comment by caldav** [comment]
Thank you for catching this!

**Comment by caldav** [comment]
And to answer your question, yes, the description is in the "How to write a tutorial" tutorial https://tutorials.ubuntu.com/tutorial/tutorial-guidelines#2
