### ISSUE TITLE
Update image on the "Create a bootable USB stick on macOS" tutorial

### ISSUE THREAD

**Issue by rishabhsrao** [canonical-websites/tutorials.ubuntu.com#662]
Hi!

I was going through the [Create a bootable USB stick on macOS](https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-macos#2) tutorial and noticed that step 4 says...

> Set the format to `MS-DOS (FAT)` and the scheme to `GUID Partition Map`

... but the screenshot does not display the **Scheme** dropdown. Here's a screenshot of what I'm talking about _(I've annotated the areas of interest with a red box)_:

<img width="1050" alt="No Scheme dropdown" src="https://user-images.githubusercontent.com/342789/36187537-d1636098-10fa-11e8-8957-f81d45488db2.png">

I found that I have this option on my Macbook and I took a screenshot of it:

<img width="932" alt="My screenshot has the Scheme dropdown" src="https://user-images.githubusercontent.com/342789/36187570-fdfeafae-10fa-11e8-8b51-c9377a9b60de.png">

I thought of creating a pull request to fix this in [create-a-usb-stick-on-macos.md](https://github.com/canonical-websites/tutorials.ubuntu.com/blob/751589f43acb181587c9ef3b7e3cd0fab0c915a6/tutorials/desktop/create-a-usb-stick-on-macos/create-a-usb-stick-on-macos.md#prepare-the-usb-stick), but I don't know how to upload this image asset to the `assets.ubuntu.com` server e.g. `https://assets.ubuntu.com/v1/b50caa3d-macos-usb-format.png`. Looks like it requires an API token. How do I generate one? Otherwise, feel free to take the above image, upload it and update the URL in [create-a-usb-stick-on-macos.md](https://github.com/canonical-websites/tutorials.ubuntu.com/blob/751589f43acb181587c9ef3b7e3cd0fab0c915a6/tutorials/desktop/create-a-usb-stick-on-macos/create-a-usb-stick-on-macos.md#prepare-the-usb-stick). Either way is fine.

Thanks!

**Comment by caldav** [comment]
Good catch! Thanks for the screenshot, I'm replacing the current one with yours.

A note on images is indeed missing in the contribution guidelines. They should probably mention that assets.ubuntu.com is an access-controlled file hosting service used by the Canonical web team to host images for Ubuntu related websites. Images can also live in the repo along the tutorial itself and any images re-hosting - if needed - is taken care of by the PR reviewer.

**Comment by rishabhsrao** [comment]
@caldav Great! Thank you!

**Comment by y3sh** [comment]
In going through the tutorial with the latest MacOS, it seems Apple hides the root flash drive by default now on some devices. In this case, the "GUID partition map" is not in the default view anymore, nor is it the default.

It would be good to update the instructions on this page to:
- Open Disk Utility
- Click on View
- Show all devices
- Click on the highest level of your flash drive
- Click erase
- Now click GUID Partition Map

See below

![screen shot 2018-04-26 at 3 09 46 pm](https://user-images.githubusercontent.com/1032983/39329517-2d71d026-4964-11e8-97e5-e200256f8f50.png)

![screen shot 2018-04-26 at 3 11 17 pm](https://user-images.githubusercontent.com/1032983/39329533-33b7311a-4964-11e8-8f5d-b54aa935c04d.png)
