### ISSUE TITLE
[Install Ubuntu on a Chromebook] Doesn't work with Tegra based models

### ISSUE THREAD

**Issue by ldesousa** [canonical-websites/tutorials.ubuntu.com#676]
<describe the issue>
This tutorial does not work on my Acer Chromebook 13. You should list the models for which the tutorial applies.

**Comment by evilnick** [comment]
Thanks for reporting an issue. It would be helpful to know how/why it seems that it doesn't work for you?

**Comment by ldesousa** [comment]
I already did. This tutorial only applies to a subset Chromebook models. All you need to replicate the issue is follow the process on a Chromebook 13.
