### ISSUE TITLE
[Create your first snap] install snapcraft through snap

### ISSUE THREAD

**Issue by abitrolly** [canonical-websites/tutorials.ubuntu.com#692]
Official docs advise installing `snapcraft` through `snap` - https://docs.snapcraft.io/build-snaps/get-started-snapcraft
```
snap install snapcraft --classic
```
but tutorial proposes to use `apt`.

**Comment by Lin-Buo-Ren** [comment]
Also, whichever form the snapcraft release is used shouldn't matter as *as of now* either the two distributions ship the same release and is not freezed like generic Ubuntu packages.
