### ISSUE TITLE
[Upgrade Ubuntu desktop] Can't upgrade from 17.04 to 17.10 as tutorial indicates

### ISSUE THREAD

**Issue by NemanSyed** [canonical-websites/tutorials.ubuntu.com#701]
I'm running 17.04, and need to upgrade to 17.10 or wait for 18.04. The tutorial at https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-ubuntu?_ga=2.66438059.442286430.1523222278-593375689.1508616882#0 quite clearly indicates:
1. Overview
With a bootable Ubuntu USB stick, you can:
Install or upgrade Ubuntu

However, if you follow the instructions, you will create a bootable USB key that will only let you try or install. There is no upgrade option at all.

- How do I upgrade from 17.04 to 17.10 without destroying my setup? (Is https://help.ubuntu.com/community/EOLUpgrades going to work? I can't spare the time to go through it - I need a simple upgrade path or just know reinstallation is my only option.)
- Should I just wait for 18.04 LTS later this month?
- Will I be stuck in the same situation once 18.04 LTS comes out?

**Comment by evilnick** [comment]
The tutorials are currently being updated, but you don't need to download a USB stick, you can upgrade from within your current distro:

https://tutorials.ubuntu.com/tutorial/tutorial-upgrading-ubuntu-desktop#0

N.B. that tutorial will shortly be updated too, to reflect 18.04
