### ISSUE TITLE
Type in code: Setting up the VirtualHost Configuration File

### ISSUE THREAD

**Issue by deleteZombie** [canonical-websites/tutorials.ubuntu.com#754]
on this page:
https://tutorials.ubuntu.com/tutorial/install-and-configure-apache#3

the line:
sudo cp 000-defualt.conf gci.conf
should be:
sudo cp 000-default.conf gci.conf

**Comment by nottrobin** [comment]
This has been fixed in https://github.com/canonical-websites/tutorials.ubuntu.com/commit/b58866b9fa84ea9ff1d9866d91723824fc11e0e6
