### ISSUE TITLE
[Upgrade Ubuntu desktop] <please add a title>

### ISSUE THREAD

**Issue by bealljohn** [canonical-websites/tutorials.ubuntu.com#815]
Way to long to find my issue. wanted to completely remove My Weather indicator, Synoptic didn't do it!

**Comment by evilnick** [comment]
The tutorial is for upgrading your desktop software, not uninstalling things. 
Though an 'uninstall' tutorial is a good idea.

**Comment by bealljohn** [comment]
Thanks Nick,

I have done some things that make my desktop look a little Better using a
little upgrade to gnome and installing gnome Tweek, sorry about the
Spelling as I'm on my Phone now!

Thanks for replying. Til next Time I'm stuck!

John Beall
