### ISSUE TITLE
STUPID GUIDES!! DON'T WORK, WRONG INSTRUCTIONS!1[Install Ubuntu desktop] <please add a title>

### ISSUE THREAD

**Issue by tuubuu** [canonical-websites/tutorials.ubuntu.com#820]
For gawd's sake, am tyring to install ubuntu and the guide says it has tutorials on how to make the download dvd and instead it shows you how to make a normal, movie or such dvd!! You can't make a normal dvd on ubuntu if you haven't got it installed!! And that's not the only problem- in another area is tells how to do this, to install from a dvd and says use Rufus. But Rufus doesn't work on XP which is what I specifically asked for! And no other option presented. Is it impossible now to use ubuntu on an XP system??
 I know, I know, I'm a dinosaur but everything implies it will work but after a day at it,,,, nothing! Every step of the way has been a hassle. I'm off to Microsoft, damn them.

**Comment by tuubuu** [comment]
,,, and at one point the instruction say to open the .iso file. Well, which one?? All of them? The whole download package? Put in a picture or some better explanation,,,, redo the whole thing!!!

**Comment by pmahnke** [comment]
@tuubuu 	sorry you are having issues, it does say on requirements that you need media and to look on the homepage to get the type you need... for example dvd buring one is here: https://tutorials.ubuntu.com/tutorial/tutorial-burn-a-dvd-on-windows#0

there are also ones for usb for windows, mac and ubunut

good luck
