### ISSUE TITLE
Tutorials: Add 'any tutorials we've missed' to the footer

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/tutorials.ubuntu.com#875]
![Screenshot from 2018-05-24 15-52-13.png](https://images.zenhubusercontent.com/5a9d4ee34b5806bc2bc9694d/79b1a018-87f4-4deb-9435-e3028b492553)

**Comment by anasereijo** [comment]
@pmahnke do you know where this should link to? There's no link on the brief https://docs.google.com/document/d/1tn7QkZqLOOJlH_UHBhim5cO1bDahLFo-XeVh62cpS30/edit#
