### ISSUE TITLE
Tutorials: remove text when searching

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/tutorials.ubuntu.com#887]

**Comment by anasereijo** [comment]
### Desktop

![tutorials hp search](https://user-images.githubusercontent.com/36884067/48711603-8da11000-ec03-11e8-9966-10c92fcad685.jpg)


### Mobile
![mobile search](https://user-images.githubusercontent.com/36884067/48711709-d5c03280-ec03-11e8-9c50-b31a9dd4297b.png)
