### ISSUE TITLE
Writing image stops working while downloading 'ldlinux.sys'

### ISSUE THREAD

**Issue by jaggiJ** [canonical-websites/tutorials.ubuntu.com#891]
OS: Win7 32bit SP1

1. Run rufus 3.3.1400 
2. Select image lubuntu
3. Start
4. Choose yes to download additional files
5. it stops working, its taskbar icon has green background.

![issue](https://user-images.githubusercontent.com/18056024/48913205-ff818f80-ee77-11e8-8739-1b35d9f7f106.png)

**Comment by pmahnke** [comment]
@jaggiJ 	I don't know what to tell you. Perhaps try the lbuntu folks? 

This isn't a support site... so closing.
