### ISSUE TITLE
[Install and Configure Apache] <please add a title>

### ISSUE THREAD

**Issue by nikunjsoni001** [canonical-websites/tutorials.ubuntu.com#893]
Provided steps are not giving the expected result . i have installed the Apache . and followed all your steps . and performing those step in elementary OS one of Ubuntu flavor . When i am using localhost it is working but when i am am using particular server name it is not working

**Comment by pmahnke** [comment]
sorry you had a problem, sounds like a hosts file (as in you need to add the name to it) issue that's been reported, I am closing this as a dupe
