### ISSUE TITLE
Anaconda on chromebook

### ISSUE THREAD

**Issue by Valentin335** [canonical-websites/tutorials.ubuntu.com#897]
![screenshot 2018-12-08 at 12 17 01](https://user-images.githubusercontent.com/45711601/49685445-aa828200-fae3-11e8-95c6-9c3433a8585d.png)
![screenshot 2018-12-08 at 11 53 59](https://user-images.githubusercontent.com/45711601/49685446-aa828200-fae3-11e8-8dca-c750113fe587.png)
 I tried 2 tutorials to finnaly get anaconda and nothing is working, here is tutorials : 
https://tutorials.ubuntu.com/tutorial/install-ubuntu-on-chromebook#2
https://wsvincent.com/install-python3-chromebook/
thk you in advance

**Comment by pmahnke** [comment]
@Valentin335 	thanks, we got another issue on the password, so I am closing this.
