### ISSUE TITLE
How to overcome "failed to load ldlinux.c32 file" while installing ubuntu

### ISSUE THREAD

**Issue by osahady** [canonical-websites/tutorials.ubuntu.com#899]
<describe the issue>
When trying to install ubuntu an error message appear just after the the usb flash has been inserted . . . 
Failed to load ldlinux.c32 file . . . 
How to solve this ?

**Comment by pmahnke** [comment]
@osahady 	I am not sure the error and this isn't a support site; however, it sounds like a 64 vs 32 bit issue. Try AskUbuntu? https://askubuntu.com/questions/924005/can-ubuntu-64bit-be-installed-on-a-32bit-computer

closing
