### ISSUE TITLE
[Create a bootable USB stick on Windows] <please add a title>

### ISSUE THREAD

**Issue by JeTSpice** [canonical-websites/tutorials.ubuntu.com#910]
<describe the issue> maybe a link to "how to boot up ubuntu on a usb"

**Comment by pmahnke** [comment]
@JeTSpice 	as in a live boot? or to install?

**Comment by JeTSpice** [comment]
sorry, couple months have passed and i don't know what my question was referring to.

**Comment by pmahnke** [comment]
no worries
