### ISSUE TITLE
[Install Ubuntu desktop] <please add a title>

### ISSUE THREAD

**Issue by anuuu16** [canonical-websites/tutorials.ubuntu.com#935]
The installation is stuck after the restart now button shows.
It's hangs after that with dual windows installation

**Comment by pmahnke** [comment]
@anuuu16 	this site is for tutorial bugs and code.  I think you should try askubuntu.com for support.  or google around - https://www.google.com/search?q=ubuntu+The+installation+is+stuck+after+the+restart+now+button+shows.+It%27s+hangs+after+that+with+dual+windows+installation&oq=ubuntu+The+installation+is+stuck+after+the+restart+now+button+shows.+It%27s+hangs+after+that+with+dual+windows+installation&aqs=chrome..69i57j0l5.1937j1j4&sourceid=chrome&ie=UTF-8

sorry I can't offer any suggestions

closing
