### ISSUE TITLE
[Create a bootable USB stick on Ubuntu] <please add a title>

### ISSUE THREAD

**Issue by randyman99** [canonical-websites/tutorials.ubuntu.com#940]
My understanding is that this tutorial is to install an Ubuntu installation ISO file to a USB drive. I want to install an already installed Ubuntu installation, configured the way I like it, to a USB drive.

**Comment by pmahnke** [comment]
@randyman99 I think what you want is what is called a 'live' or 'bootable' usb.  it can be done!

I don't think we have a tutorial for that... try https://www.google.com/search?q=create+a+live+usb+with+ubuntu&oq=create+a+live+usb+with+ubuntu&aqs=chrome..69i57j0l5.7279j1j4&sourceid=chrome&ie=UTF-8

sorry I cannot offer more help.

closing this issue.
