### ISSUE TITLE
[Install Ubuntu desktop] <please add a title>

### ISSUE THREAD

**Issue by danmorgan47** [canonical-websites/tutorials.ubuntu.com#942]
My new computer arrived with Windows 10 installed.  I want to partition the disk to have Ubuntu as preference but Windows as an option.  How do I do this?  Do I need the license code for my copy of Windows?

**Comment by pmahnke** [comment]
@danmorgan47 you will not be asked for a license code while installing Ubuntu, but you might need it for Windows... 

this isn't a help site, perhaps try ask ubuntu?

https://askubuntu.com/questions/221835/how-do-i-install-ubuntu-alongside-a-pre-installed-windows-with-uefi

closing
